added example for deploying ubuntu 2004 packer machine image #92
tinkerbell/tinkerbell-docs pull request #100
Opened 2021-04-02 14:39 UTC by Cbkhare

## Description

This PR adds an example of how to create and deploy packer machine image using Tinkerbell. 

## How Has This Been Tested?
- Vagrant setup with Virtual box provider.

2021-04-02 14:46 UTC, markyjackson-taulia requested changes
Minor grammer changes

2021-04-02 14:46 UTC, markyjackson-taulia commented on docs/deploying-operating-systems/examples-ubuntu-packer.md
> +This guide will walk you through how you create a minimalistic raw Ubuntu image using the Packer which can be deployed on a bare metal server using the Tinkerbell.
I feel like this `using the Tinkerbell.` should read `using Tinkerbell.`

2021-04-02 14:46 UTC, markyjackson-taulia commented on docs/deploying-operating-systems/examples-ubuntu-packer.md
> +[Packer](https://www.packer.io/) is an awesome tool to build automated machine images. Currently, the Packer doesnot officially provide a way to make bare metal machine images. So in this example, we
`doesnot` should be `does not`

2021-04-02 14:46 UTC, markyjackson-taulia commented on docs/deploying-operating-systems/examples-ubuntu-packer.md
> +[Packer](https://www.packer.io/) is an awesome tool to build automated machine images. Currently, the Packer doesnot officially provide a way to make bare metal machine images. So in this example, we
`So in this example` should be `So, in this example`

2021-04-05 04:56 UTC, Cbkhare commented on docs/deploying-operating-systems/examples-ubuntu-packer.md
> +[Packer](https://www.packer.io/) is an awesome tool to build automated machine images. Currently, the Packer doesnot officially provide a way to make bare metal machine images. So in this example, we
done

2021-04-05 04:56 UTC, Cbkhare commented on docs/deploying-operating-systems/examples-ubuntu-packer.md
> +[Packer](https://www.packer.io/) is an awesome tool to build automated machine images. Currently, the Packer doesnot officially provide a way to make bare metal machine images. So in this example, we
done

2021-04-05 04:56 UTC, Cbkhare commented on docs/deploying-operating-systems/examples-ubuntu-packer.md
> +This guide will walk you through how you create a minimalistic raw Ubuntu image using the Packer which can be deployed on a bare metal server using the Tinkerbell.
done

2021-04-05 05:45 UTC, markyjackson-taulia approved these changes

2021-04-06 14:36 UTC, DailyAlice approved these changes
I'm going to go ahead and approve; thinking I would just do the same as the other OS docs, merge and then PR with a couple of markdown fixes and adding it to the toc (mkdocs.yml).

2021-04-06 14:36 UTC, merged