Update Local setup with Vagrant documentation
tinkerbell/tinkerbell-docs pull request #132
Opened 2021-12-01 20:45 UTC by cprivite

## Description

Update the Local Setup with Vagrant setup guide to work with the current version of Sandbox. 

## Why is this needed

Fixes: The guide as written doesn't work due to many changed directory paths, conflicting MAC addresses in the guide already existing in the repo, the docker registry requiring SSL now by default, and more. This is just a quick cleanup to make it at least function as written.

## How Has This Been Tested?

Ran through the setup and validated the examples worked and provided the stated output.

Linux Ubuntu 20.04 with libvirt.

It doesn't touch any code, just this one documentation file.

## How are existing users impacted? What migration steps/scripts do we need?

Documentation will actually work for the vagrant setup workflow.

## Checklist:

I have:

- [X] updated the documentation and/or roadmap (if required)
- [O] added unit or e2e tests
- [O] provided instructions on how to upgrade

2021-12-08 19:41 UTC, cprivite commented
Based on suggestions, I reviewed my changes and made the following updates. 

1. Removed an unnecessary docker-compose up -d
2. Figured out how to import the SSL cert so we can stick to using normal docker tooling for uploading images instead of skopeo
3. Moved the part where it tells you how to tail the logs to after the SSL cert import, since it involves restarting docker
4. Instead of editing the vagrant file (which wasn't working as well as I though it was anyway), now I just have the user remove the Tinkerbell hardware and workflow templates from the compose directory. This enables the later steps of creating hardware and workflows to work without issue.
5. Tested on both vagrant and libvirt.

2021-12-14 16:11 UTC, displague commented on docs/setup/local-vagrant.md
> +First we need to delete the default template and hardware definition that the sandbox repo comes with. This let's us practice setting up the template and workflow in tinkerbell without any conflicts
```suggestion
First we need to delete the default template and hardware definition that the sandbox repo comes with. This lets us practice setting up the template and workflow in tinkerbell without any conflicts with what comes pre-defined in the sandbox repo.
```

2021-12-14 16:23 UTC, displague commented on docs/setup/local-vagrant.md
> +Tinkerbell is going to be running from a container, so navigate to the `/vagrant/compose` directory, so navigate to the `/vagrant/compose` directory and load up the .env file that has all our environ
```suggestion
Tinkerbell is going to be running from a container, so navigate to the `/vagrant/compose` directory and load up the .env file that has all our environment's settings in it, and start the Tinkerbell stack with `docker-compose`.
```

2021-12-14 16:27 UTC, displague commented on docs/setup/local-vagrant.md
> +As you'll see shortly, each step in a Tinkerbell workflow is referred to as an Action Image, and is simply a Docker image. Before you move ahead, let's pull down the image that will be used in the ex
```suggestion
As you'll see shortly, each step in a Tinkerbell workflow is referred to as an Action Image, and is simply a Docker image. Before you move ahead, let's pull down the image that will be used in the example workflow. Tinkerbell uses Docker registry to host images locally, so pull down the ["Hello World" docker image](https://hub.docker.com/_/hello-world/) and push it to the registry.
```

2021-12-14 16:34 UTC, displague requested changes
I've offered some minor white-space changes for markdown readability. Looks good otherwise.

2021-12-14 16:34 UTC, displague commented on docs/setup/local-vagrant.md
> +First, define the Worker's hardware data, which is used to identify the Worker as the target of a workflow. Very minimal hardware data is required for this example, but it does at least need to conta
```suggestion
First, define the Worker's hardware data, which is used to identify the Worker as the target of a workflow. Very minimal hardware data is required for this example, but it does at least need to contain the MAC Address of the Worker, which is hardcoded in the Vagrant file, and have the Worker set to allow PXE booting and accept workflows.
```

2021-12-14 16:34 UTC, displague commented on docs/setup/local-vagrant.md
> +Then, push the hardware data to the database with the `tink hardware push` command.
```suggestion
Then, push the hardware data to the database with the `tink hardware push` command.
```

2021-12-14 16:34 UTC, displague commented on docs/setup/local-vagrant.md
> +At this point, you might want to open a separate terminal  window to show logs from the Provisioner, because it will show what the `tink-server` is doing through the rest of the setup. Open a new ter
```suggestion

At this point, you might want to open a separate terminal  window to show logs from the Provisioner, because it will show what the `tink-server` is doing through the rest of the setup. Open a new terminal, ssh in to the provisioner as you did before, and run `docker-compose logs -f` to tail logs.
```

2021-12-14 16:34 UTC, displague commented on docs/setup/local-vagrant.md
> +Then let's login, get the image, and upload it to our registry.
```suggestion

Then let's login, get the image, and upload it to our registry.

```

2021-12-14 16:34 UTC, displague commented on docs/setup/local-vagrant.md
> +Let's trust the SSL certs of the registry container.
```suggestion
Let's trust the SSL certs of the registry container.

```

2022-01-12 15:12 UTC, displague commented
@cprivite It looks like this needs a rebase, unless mergify is supposed to be able to handle that.

I can merge after that (blocked until then).  
If you do rebase, perhaps you can see if there are any outstanding dead-links that you can pick up in this doc update (definitely not a requirement to merge here).

https://github.com/tinkerbell/tinkerbell-docs/issues/42

2022-01-12 15:16 UTC, displague commented
@Mergifyio rebase

2022-01-12 19:08 UTC, merged