Add chrisdoherty4 as maintainer
tinkerbell/tinkerbell-docs pull request #164
Opened 2022-12-24 19:04 UTC by chrisdoherty4

2022-12-31 00:00 UTC, displague requested changes

2022-12-31 00:00 UTC, displague commented on .github/settings.yml
> +    permission: maintain
This line seems wrong

2023-01-03 00:02 UTC, chrisdoherty4 commented on .github/settings.yml
> +    permission: maintain
You mean there's a typo or something?

2023-01-23 20:16 UTC, displague approved these changes

2023-01-24 15:04 UTC, DailyAlice approved these changes

2023-01-24 15:14 UTC, merged