Qemu
tinkerbell/tinkerbell-docs pull request #67
Opened 2021-01-27 11:12 UTC by thebsdbox

## Description

This adds the basic usage of Bare Metal with Qemu for the deployment hosts.

## Why is this needed

Adds more ways to use Tinkerbell !

Fixes: #

## How Has This Been Tested?

This has been used to implement new features in Tinkerbell !

## How are existing users impacted? What migration steps/scripts do we need?

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

2021-01-27 11:36 UTC, gianarb reviewed
Great work!

2021-01-27 11:36 UTC, gianarb commented on docs/setup/using-qemu.md
> +- Equinix Metal portal account
Is sit this needed? I presume everything that can run Qemu with a reasonable amount of memory and CPU is fine, I would like to change that in favor of something more generic

2021-01-27 11:36 UTC, gianarb commented on docs/setup/using-qemu.md
> +### In memory OS (OSIE)
This should be: "Operating System installation environment" and I am not sure we need it, we can link to this guide https://docs.tinkerbell.org/services/osie/ and leave only what is required for this document

2021-01-27 11:36 UTC, gianarb commented on docs/setup/using-qemu.md
> +### Recomended Machine size or Equinix Metal instances and OS
Move this to prerequisite and avoid specifying a concrete provider IMHO.

2021-01-27 11:36 UTC, gianarb commented on docs/setup/using-qemu.md
> +### Install sandbox dependencies
I think this is almost the same guide I wrote here #66 I would like to merge a few of those commands there and link it to it from here (the fewest information we duplicate the easier documentation will be to maintain)

2021-01-27 12:35 UTC, gianarb requested changes
This requires a bit of manipulation based on #66 and it has to be merged after that.

2021-01-28 11:53 UTC, thebsdbox commented
Addressed your changes :-)  and fixed conflict

2021-01-29 10:19 UTC, gianarb approved these changes
Perfect!

2021-02-01 19:09 UTC, DailyAlice approved these changes

2021-02-01 19:09 UTC, thebsdbox commented on docs/setup/using-qemu.md
> +## Deploying Tinkerbell
sure

2021-02-01 19:10 UTC, thebsdbox commented on docs/setup/using-qemu.md
> +## Create a workflow (debian example)
Yeah, makes sense :)

2021-02-01 19:10 UTC, merged